package com.emse.spring.automacorp.model;

import jakarta.persistence.*;

import java.util.Set;

@Entity
@Table(name = "SP_BUILDING")
public class BuildingEntity {
    /**
     * A BuildingEntity is the representation of a building within our database.
     * It has an autogenerated id, an outside temperature and a list of rooms.
     */
    @Id
    @GeneratedValue
    private Long id;

    @Column(nullable=false)
    private String name;

    @OneToOne
    private SensorEntity outsideTemperature;

    @OneToMany(mappedBy = "building", fetch = FetchType.EAGER)
    private Set<RoomEntity> rooms = Set.of();


    public BuildingEntity(){};

    public BuildingEntity(String name, SensorEntity outsideTemperature){
        this.name = name;
        this.outsideTemperature = outsideTemperature;
    }


    public Long getId() {return id;}

    public void setId(Long id) {this.id = id;}

    public String getName() {return name;}

    public void setName(String name) {this.name = name;}

    public SensorEntity getOutsideTemperature() {return outsideTemperature;}

    public void setOutsideTemperature(SensorEntity outsideTemperature) {this.outsideTemperature = outsideTemperature;}

    public Set<RoomEntity> getRooms() {return rooms;}

    public void setRooms(Set<RoomEntity> rooms) {this.rooms = rooms;}
}
