package com.emse.spring.automacorp.model;

import jakarta.persistence.*;

@Entity
@Table(name = "SP_HEATER")
public class HeaterEntity {
    /**
     * A HeaterEntity is the representation of a heater within our database.
     * It has an autogenerated id, a non-nullable name, a power, a status and a room.
     */

    @Id
    @GeneratedValue
    private Long id;

    @Column(nullable=false)
    private String name;

    @Column
    private Long power;

    @OneToOne(optional = false)
    private SensorEntity heaterStatus;

    @ManyToOne(optional = false)
    private RoomEntity room;


    public HeaterEntity(){};

    public HeaterEntity(String name, SensorEntity heaterStatus, RoomEntity room){
        this.name = name;
        this.heaterStatus = heaterStatus;
        this.room = room;
    }

    public HeaterEntity(String name, Long power, SensorEntity heaterStatus, RoomEntity room){
        this.name = name;
        this.power = power;
        this.heaterStatus = heaterStatus;
        this.room = room;
    }


    public Long getId() {return id;}

    public void setId(Long id) {this.id = id;}

    public Long getPower() {return power;}

    public void setPower(Long power) {this.power = power;}

    public String getName() {return name;}

    public void setName(String name) {this.name = name;}

    public RoomEntity getRoom() {return room;}

    public void setRoom(RoomEntity room) {this.room = room;}

    public SensorEntity getHeaterStatus() {return heaterStatus;}

    public void setHeaterStatus(SensorEntity heaterStatus) {this.heaterStatus = heaterStatus;}
}
