package com.emse.spring.automacorp.model;

import jakarta.persistence.*;

import java.util.Set;

@Entity
@Table(name = "SP_ROOM")
public class RoomEntity {
    /**
     * A RoomEntity is the representation of a room within our database.
     * It has an autogenerated id, a non-nullable floor, a non-nullable name, a current temperature measured
     *  by a sensor, a target temperature, a list of windows, a list of heaters and a non-nullable building.
     */
    @Id
    @GeneratedValue
    private Long id;

    @Column(nullable=false)
    private Integer floor;

    @Column(nullable=false)
    private String name;

    @OneToOne
    private SensorEntity currentTemperature;

    @Column
    private Double targetTemperature;

    @OneToMany(mappedBy = "room", fetch = FetchType.EAGER)
    private Set<WindowEntity> windows = Set.of();

    @OneToMany(mappedBy = "room", fetch = FetchType.EAGER)
    private Set<HeaterEntity> heaters = Set.of();

    @ManyToOne(optional = false)
    private BuildingEntity building;


    public RoomEntity(){}

    public RoomEntity(String name, SensorEntity current_temperature, Integer floor, BuildingEntity building){
        this.floor = floor;
        this.name = name;
        this.currentTemperature = current_temperature;
        this.building = building;
    }

    public RoomEntity(Integer floor, String name, SensorEntity current_temperature, Double target_temperature, BuildingEntity building){
        this.floor = floor;
        this.name = name;
        this.currentTemperature = current_temperature;
        this.targetTemperature = target_temperature;
        this.building = building;
    }


    public Long getId() {return id;}

    public void setId(Long id) {this.id = id;}

    public Integer getFloor() {return floor;}

    public void setFloor(Integer floor) {this.floor = floor;}

    public String getName() {return name;}

    public void setName(String name) {this.name = name;}

    public SensorEntity getCurrentTemperature() {return currentTemperature;}

    public void setCurrentTemperature(SensorEntity current_temperature) {this.currentTemperature = current_temperature;}

    public Double getTargetTemperature() {return targetTemperature;}

    public void setTargetTemperature(Double target_temperature) {this.targetTemperature = target_temperature;}

    public Set<WindowEntity> getWindows() {return windows;}

    public void setWindows(Set<WindowEntity> windows) {this.windows = windows;}

    public Set<HeaterEntity> getHeaters() {return heaters;}

    public void setHeaters(Set<HeaterEntity> heaters) {this.heaters = heaters;}

    public BuildingEntity getBuilding() {return building;}

    public void setBuilding(BuildingEntity building) {this.building = building;}
}
